// Backend/src/utils/cashfree.js
const axios = require("axios");

// IMPORTANT: Load your environment variables here
// For this example, we'll assume you have a config or .env file loader
const CASHFREE_APP_ID = process.env.CASHFREE_APP_ID;
const CASHFREE_SECRET_KEY = process.env.CASHFREE_SECRET_KEY;
const CASHFREE_API_URL = process.env.CASHFREE_API_URL || "https://api.cashfree.com/pg/orders";

const headers = {
  "Content-Type": "application/json",
  "x-client-id": CASHFREE_APP_ID,
  "x-client-secret": CASHFREE_SECRET_KEY,
  "x-api-version": "2022-09-01",
};

/**
 * Calls the Cashfree API to create a payment order.
 * @param {object} orderData - Data required for the order, including amount and customer details.
 */
async function PGCreateOrder(orderData) {
  try {
    const response = await axios.post(CASHFREE_API_URL, orderData, { headers });
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Cashfree PGCreateOrder Error:", error.response?.data || error.message);
    return { 
      success: false, 
      error: error.response?.data?.message || "Failed to create order with Cashfree" 
    };
  }
}

/**
 * Calls the Cashfree API to fetch the final order status.
 * @param {string} orderId - The unique order ID generated by your system.
 */
async function PGFetchOrder(orderId) {
  try {
    const fetchUrl = `${CASHFREE_API_URL}/${orderId}`;
    const response = await axios.get(fetchUrl, { headers });
    return { success: true, data: response.data };
  } catch (error) {
    console.error("Cashfree PGFetchOrder Error:", error.response?.data || error.message);
    return { 
      success: false, 
      error: error.response?.data?.message || "Failed to fetch order status from Cashfree" 
    };
  }
}

module.exports = {
  PGCreateOrder,
  PGFetchOrder,
};