// Backend/models/Booking.js
'use strict';
const { Model } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
  class Booking extends Model {
    static associate(models) {
      // Associations are in server.js
    }
  }
  Booking.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    clientId: {
      type: DataTypes.CHAR(36),
      allowNull: false,
      references: {
        model: 'users',
        key: 'id',
      },
      onDelete: 'CASCADE', 
    },
    sessionId: { 
      type: DataTypes.CHAR(36),
      allowNull: false, 
      references: {
        model: 'coach_sessions', 
        key: 'id',
      },
      onDelete: 'CASCADE', 
    },
    // --- NEW FIELDS FOR PAYMENT INTEGRATION ---
    paymentOrderId: { // Unique Order ID generated by your system
      type: DataTypes.STRING(100),
      unique: true,
      allowNull: true, // It might be null until the payment process starts
    },
    paymentSessionId: { // Session ID from the Payment Gateway
      type: DataTypes.STRING(255),
      allowNull: true,
    },
    // --- UPDATED STATUS ENUM ---
    status: {
      type: DataTypes.ENUM('order_initiated', 'order_created', 'payment_success', 'payment_failed', 'confirmed', 'pending', 'cancelled', 'completed'), 
      defaultValue: 'order_initiated',
      comment: 'Tracks booking and payment status.',
    },
    // ------------------------------------------
    isReviewed: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
      comment: 'Flag to prevent multiple testimonials for the same booking.'
    },
    bookedAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
  }, {
    sequelize,
    modelName: 'Booking',
    tableName: 'client_bookings',
    timestamps: true,
  });
  return Booking;
};